### ISSUE TITLE
Gitignore is not created when running varan init

### ISSUE THREAD

**Issue by MagneH** [ersims/varan#5]
Gitignore is not created when running varan init. Possibly due to some conflict with the varan project's own gitignore file.

**Comment by ersims** [comment]
Which version are you using? This should have been fixed in [be6fcc5c87](https://github.com/ersims/varan/blob/be6fcc5c874affabd46c6036ae9441104a21749c/examples/advanced/v-keep-.gitignore) and included in the [v0.2.6](https://github.com/ersims/varan/releases/tag/v0.2.6) release.

**Comment by MagneH** [comment]
Updated now! Great job!
